# Generated by Django 5.2.4 on 2026-05-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISummaryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='關鍵字')),
                ('summary', models.TextField(verbose_name='摘要（Markdown）')),
                ('sources', models.JSONField(default=list, verbose_name='來源文章')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'AI 摘要快取',
                'verbose_name_plural': 'AI 摘要快取',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='關鍵字')),
                ('keyword_zh', models.CharField(blank=True, max_length=255, verbose_name='中文名稱')),
                ('keyword_en', models.CharField(blank=True, max_length=255, verbose_name='英文全名')),
                ('keyword_abbr', models.CharField(blank=True, max_length=100, verbose_name='英文縮寫')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '關鍵字',
                'verbose_name_plural': '關鍵字',
            },
        ),
        migrations.CreateModel(
            name='KeywordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '關鍵字分類',
                'verbose_name_plural': '關鍵字分類',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='群組名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '關鍵字群組',
                'verbose_name_plural': '關鍵字群組',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'main'), (2, 'sub'), (3, 'third')], verbose_name='層級')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.articlegroup', verbose_name='上層群組')),
            ],
            options={
                'verbose_name': '文章群組',
                'verbose_name_plural': '文章群組',
                'unique_together': {('parent', 'level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='標題')),
                ('content', models.TextField(blank=True, verbose_name='內容（Markdown）')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='knowledge.articlegroup', verbose_name='文章群組')),
                ('keywords', models.ManyToManyField(blank=True, related_name='articles', to='knowledge.keyword', verbose_name='關鍵字')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='knowledge.keywordcategory', verbose_name='分類'),
        ),
        migrations.AddField(
            model_name='keywordcategory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='knowledge.keywordgroup', verbose_name='群組'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='問題')),
                ('answer', models.TextField(verbose_name='答案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('keywords', models.ManyToManyField(blank=True, related_name='questions', to='knowledge.keyword', verbose_name='關鍵字')),
            ],
            options={
                'verbose_name': '問答',
                'verbose_name_plural': '問答',
            },
        ),
        migrations.AlterUniqueTogether(
            name='keywordcategory',
            unique_together={('group', 'name')},
        ),
    ]
